### PR TITLE
Copy lib files to Jetty. Fixes #1.

### LINKED ISSUE #1: Solr Fails to start missing SLF4j
2013-08-03 17:00:23.929:WARN:oejuc.AbstractLifeCycle:FAILED SolrRequestFilter: org.apache.solr.common.SolrException: Could not find necessary SLF4j logging jars. If using Jetty, the SLF4j logging jars need to go in the jetty lib/ext directory. For other containers, the corresponding directory should be used. For more information, see: http://wiki.apache.org/solr/SolrLogging
org.apache.solr.common.SolrException: Could not find necessary SLF4j logging jars. If using Jetty, the SLF4j logging jars need to go in the jetty lib/ext directory. For other containers, the corresponding directory should be used. For more information, see: http://wiki.apache.org/solr/SolrLogging

### PR DESCRIPTION
**Pull request by grahambates**
Added a block to copy external libs that are no longer included in the .war file from Solr 4.3 onwards.

### CODE REVIEW

**Comment by lbdremy** [comment]
Hello @grahambates,

Thanks for that.
I will try that tonight and merge it after.

hey @rposborne could you try this patch on your end? Thanks :)

File: recipes/default.rb [hunk 1]
```diff
@@ -102,6 +102,20 @@
...
+    ext_dir = File.join(node['jetty']['home'],'/lib/ext')
+    
+    Chef::Log.info "Copying #{lib_files} into #{ext_dir}"
+    FileUtils.cp_r(lib_files, ext_dir)
+    raise "Failed to copy ext lib files" unless !Dir.glob(File.join(ext_dir, 'log4j-*.jar')).empty?
+  end
+
+  action :create
+  notifies :restart, "service[jetty]"
+end
```
Comment (motns) [inline recipes/default.rb:121]: Looks good at first glance, but you might want to add a `not_if` condition to this, otherwise it will be executed on each Chef run, restarting Jetty in the process. You can probably just use the same check that you run on line 112 to see if the files were copied...
